// <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
// $$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
// <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

#[derive(Debug, Clone, Copy)]
struct FibonacciTrible {
    a: u32,
    b: u32,
    c: u32,
}

impl FibonacciTrible {
    fn new(a: u32, b: u32, c: u32) -> Self {
        FibonacciTrible { a, b, c }
    }

    fn move_next(&mut self) {
        std::mem::swap(&mut self.a, &mut self.b);
        std::mem::swap(&mut self.b, &mut self.c);
        self.c = self.a + self.b;
    }
}


fn main() {
    let mut sum = 0u32;
    let mut triple = FibonacciTrible::new(1, 1, 2);
    while triple.c <= 4_000_000 {
        sum += triple.c;
        triple.move_next();
        triple.move_next();
        triple.move_next();
    }
    println!("{sum}");
}
