// <p>The sequence of triangle numbers is generated by adding the natural numbers. So the $7$<sup>th</sup> triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten terms would be:
// $$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \dots$$</p>
// <p>Let us list the factors of the first seven triangle numbers:</p>
// $$\begin{align}
// \mathbf 1 &amp;\colon 1\\
// \mathbf 3 &amp;\colon 1,3\\
// \mathbf 6 &amp;\colon 1,2,3,6\\
// \mathbf{10} &amp;\colon 1,2,5,10\\
// \mathbf{15} &amp;\colon 1,3,5,15\\
// \mathbf{21} &amp;\colon 1,3,7,21\\
// \mathbf{28} &amp;\colon 1,2,4,7,14,28
// \end{align}$$
// <p>We can see that $28$ is the first triangle number to have over five divisors.</p>
// <p>What is the value of the first triangle number to have over five hundred divisors?</p>

use std::collections::HashMap;

fn count_divisors(num: u32) -> usize {
    (1..=num).filter(|n| num % n == 0).count()
}

fn get_reduced_num_div(num: u32, num_div_cache: &mut HashMap<u32, usize>) -> usize {
    let key = if num % 2 == 0 { num / 2 } else { num };
    *num_div_cache.entry(key).or_insert(count_divisors(key))
}

fn main() {
    // Any triangle numbers is written by n*(n + 1)/2 for some natural number n.
    // Because n or n + 1 is even, n/2 or (n + 1)/2 is also natural number.
    // For any coprime numbers x and y, the number of divisors of xy is equal to
    // the product of the numbers of divisors of x and y.
    // Therefore, the number of divisors of n*(n + 1)/2 is
    // - (# of divisors of (n/2)) * (# of divisors of n + 1) for even n
    // - (# of divisors of n) * (# of divisors of (n + 1)/2) for odd n

    let mut num_div_cache = HashMap::new();
    let mut n = 1;
    loop {
        let num_divisors = get_reduced_num_div(n, &mut num_div_cache)
            * get_reduced_num_div(n + 1, &mut num_div_cache);
        if num_divisors > 500 {
            println!("{}: {}", n * (n + 1) / 2, num_divisors);
            break;
        }

        n += 1;
    }
}
